name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: tsc
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: intall pnpm
        uses: pnpm/action-setup@v2.0.1
      - name: init
        run: pnpm install
      - name: build
        run: pnpm run build
