name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-lates
    name: tsc
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: npm ci
      - name: build
        run: npm run build
